/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.geeklythings.fieldmarshal.ui;


//import java.util.logging.ConsoleHandler;
//import java.util.logging.Handler;
//import java.util.logging.Level;
//import java.util.logging.Logger;


import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import net.geeklythings.fieldmarshal.entity.Tournament;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


/**
 *
 * @author khooks
 */
public class LoadTournamentView extends javax.swing.JPanel implements ListSelectionListener {

    public static final String LOAD_TOURNAMENT_ID = "LoadTournamentId"; 
    private EntityManager em;         
    private static final Logger logger = LogManager.getLogger(LoadTournamentView.class.getName());
   
    private long selectedTournamentId = 0L;
    
    public long getSelectedTournamentID() {
        return selectedTournamentId;
    }
    
    /**
     * Creates new form LoadTournamentView
     */
    public LoadTournamentView() {
        
        initComponents();
        //updateList();
    }
    

    private void updateList()
    {
        // load the contents of the tournaments from the DB and display them in the list

        Query query = em.createQuery("SELECT t FROM Tournament t");
        List<Tournament> tournamentList = query.getResultList();
        logger.debug(tournamentList.toString());
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        
        if( tournamentList != null){
            for(Tournament t: tournamentList ){
                listModel.addElement(t.getId());
            }
        }
        
        tournamentJList.setModel(listModel);
        
    }
    

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        logger.debug(lse.toString());
        if(!lse.getValueIsAdjusting())
        {
/*
            int row = tableTournament.getSelectedRow();          
            int column = 0;
            logger.debug("Row {}, Column {} selected", row, column);
            Object o = tableTournament.getValueAt(row, column);          
            Long id = Long.valueOf(o.toString());        
            selectedTournamentId = id;
            
            logger.debug("Tournament selected, ID: {}", o.toString());
         */
            loadButton.setEnabled(true);
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tournamentJList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        loadButton.setText("Load");
        loadButton.setEnabled(false);
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        tournamentJList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tournamentJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        tournamentJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tournamentJList);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // notify the tournament manager that a tournament Id was selected & read
        // and to load the tournament
        firePropertyChange(LOAD_TOURNAMENT_ID, 0L, selectedTournamentId);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateList();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadButton;
    private javax.swing.JList tournamentJList;
    // End of variables declaration//GEN-END:variables

    void setEntityManager(EntityManager _em) {
        this.em = _em;
    }


}
